create table if not exists public.movies (
  id bigint generated by default as identity primary key,
  title text not null,
  actors text[] not null default '{}',
  release_year integer not null check (release_year between 1888 and 2100),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.movies enable row level security;

drop policy if exists "Authenticated users can read movies" on public.movies;
drop policy if exists "Authenticated users can insert movies" on public.movies;
drop policy if exists "Authenticated users can update movies" on public.movies;
drop policy if exists "Authenticated users can delete movies" on public.movies;

create policy "Authenticated users can read movies"
on public.movies for select
to authenticated using (true);

create policy "Authenticated users can insert movies"
on public.movies for insert
to authenticated with check (true);

create policy "Authenticated users can update movies"
on public.movies for update
to authenticated using (true) with check (true);

create policy "Authenticated users can delete movies"
on public.movies for delete
to authenticated using (true);

insert into public.movies (title, actors, release_year)
select * from (values
  ('The Matrix', ARRAY['Keanu Reeves','Laurence Fishburne','Carrie-Anne Moss'], 1999),
  ('Jurassic Park', ARRAY['Sam Neill','Laura Dern','Jeff Goldblum'], 1993),
  ('The Dark Knight', ARRAY['Christian Bale','Heath Ledger','Michael Caine'], 2008)
) as seed(title, actors, release_year)
where not exists (select 1 from public.movies);
